package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallTask;
import org.linlinjava.litemall.db.domain.LitemallTaskExample;

public interface LitemallTaskMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_task
     *
     * @mbg.generated
     */
    long countByExample(LitemallTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_task
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_task
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_task
     *
     * @mbg.generated
     */
    int insert(LitemallTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_task
     *
     * @mbg.generated
     */
    int insertSelective(LitemallTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_task
     *
     * @mbg.generated
     */
    LitemallTask selectOneByExample(LitemallTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_task
     *
     * @mbg.generated
     */
    LitemallTask selectOneByExampleSelective(@Param("example") LitemallTaskExample example, @Param("selective") LitemallTask.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_task
     *
     * @mbg.generated
     */
    List<LitemallTask> selectByExampleSelective(@Param("example") LitemallTaskExample example, @Param("selective") LitemallTask.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_task
     *
     * @mbg.generated
     */
    List<LitemallTask> selectByExample(LitemallTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_task
     *
     * @mbg.generated
     */
    LitemallTask selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallTask.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_task
     *
     * @mbg.generated
     */
    LitemallTask selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_task
     *
     * @mbg.generated
     */
    LitemallTask selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_task
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallTask record, @Param("example") LitemallTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_task
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallTask record, @Param("example") LitemallTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_task
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_task
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_task
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") LitemallTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_task
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}